apiVersion: v1
kind: Pod
metadata:
  name: gallery-project
  clusterName: kind-workloads
  namespace: default
  labels:
    app: gallery-project
spec:
  containers:
    - name: gallery-project
      image: lucas3337/gallery-project:v1
      ports:
      - name: web
        protocol: TCP
        containerPort: 9000
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
        limits:
          cpu: 300m
          memory: 200Mi
